### PR TITLE
adds quaternion type+code and boat max speed

### LINKED ISSUE #59: Update Quaternion to try and extract all values
our current reads only grab the two used values, but we should grab all four just in case

### LINKED ISSUE #60: Add boat max speed to boat_manager

### PR DESCRIPTION
**Pull request by Eein**
closes #59
closes #60

Testing Required:
Does max speed reflect the relic ship speed bonus? I do not currently have this relic on my save file.

### CODE REVIEW

**Comment by shenef** [comment]
Relic is not reflected
image

**Comment by Eein** [comment]
> Relic is not reflected image

Thanks! Can you send me saves where i can test this or find the correct value :)

**Review by orkaboy — APPROVED** [review]

**Comment by shenef** [comment]
You can get the relic in the Mirth equipment shop. If you don't have the merchant for it, you can recruit them in Docarri

**Comment by Eein** [comment]
Theres no value in the boat controller that knows about the relic; so we'll have to wait until we handle RelicManager (not super simple and we need all the guids)

**Pull request merged**
